-- CipherTool PostgreSQL/Supabase migration.

CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  login_attempts integer NOT NULL DEFAULT 0,
  blocked boolean NOT NULL DEFAULT false
);

-- Seed data intentionally omitted.
-- Do not commit real emails, password hashes, or local user records.
