-- CipherTool PostgreSQL schema for Supabase/local PostgreSQL.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  login_attempts integer NOT NULL DEFAULT 0,
  blocked boolean NOT NULL DEFAULT false,
  totp_secret varchar(64)
);

-- Seed data intentionally omitted.
-- Do not commit real emails, password hashes, or local user records.

COMMIT;
